#!/bin/sh
echo make $*
#OFFICIAL=yes OPENELEC_VERSION=8.0-bt CONCURRENCY_MAKE_LEVEL=4 DISTRO=OpenBT PROJECT=RPi ARCH=arm DEBUG=yes make $*
OFFICIAL=yes OPENELEC_VERSION=8.0-bt CONCURRENCY_MAKE_LEVEL=4 DISTRO=OpenBT PROJECT=RPi ARCH=arm make $*
