#!/bin/sh -x
/bin/mount -t proc null /proc
/bin/mount -t sysfs null /sys
/bin/mount -t devtmpfs null /dev

if ! /bin/mount -t jffs2 /dev/mtdblock6 /storage; then
/sbin/flash_eraseall -j /dev/mtd6
  if ! /bin/mount -t jffs2 /dev/mtdblock6 /storage; then
    /bin/mount -t tmpfs null /storage
  fi
fi
/bin/mount -t tmpfs null /tmp
/bin/dd if=/dev/mtd2 of=/tmp/mt7628.eeprom bs=1 count=512 skip=0
/usr/bin/swconfig dev switch0 set reset 1

exec /usr/lib/systemd/systemd
